dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
  - CF_API_URL="api.sys.evans.pal.pivotal.io"
  - CF_ORG="vton.corelogic.com"
  - CF_SPACE="sandbox"
  - CF_USERNAME="vton@corelogic.com"
  - CF_PASSWORD="dcmg6rhb"
  - GITHUB_USERNAME="Thunderrod91"
  - GITHUB_OAUTH_TOKEN=8524a51666a5cfd46f15f3401b44c4c5e3c8d50d
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Thunderrod91"
        - git config --local user.email "thunderrod91@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE
